spring.application.name=booking-service
# Server Configuration
server.port=8088

# Database Configuration (Oracle)
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=SYS as SYSDBA
spring.datasource.password=pwd
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

# Resilience4j Circuit Breaker Configuration
# The name 'availService' must match the @CircuitBreaker(name = "availService")
resilience4j.circuitbreaker.instances.availService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.availService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.availService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.availService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.availService.failureRateThreshold=50

# Resilience4j Retry Configuration
resilience4j.retry.instances.availService.maxAttempts=3
resilience4j.retry.instances.availService.waitDuration=2s

# Endpoint for Availability-Service (used in WebClient builder)
# If using Eureka, this would just be 'http://availability-service'
availability.service.url=http://localhost:8087