spring.application.name=theatre-service
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=sys as sysdba
spring.datasource.password=pwd
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# Hibernate Dialect (Determines SQL syntax optimization)
# Use Oracle12cDialect for Oracle 12c, 18c, 19c, and 21c
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# DDL Auto (None, Validate, Update, Create, Create-Drop)
spring.jpa.hibernate.ddl-auto=none

# SQL Visibility (Useful for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port = 8085 

